package com.boa.hackathon.autodocgen.service;

import com.boa.hackathon.autodocgen.model.ClassMetadata;
import com.boa.hackathon.autodocgen.model.MethodMeta;
import com.boa.hackathon.autodocgen.model.ProjectMetadata;
import com.boa.hackathon.autodocgen.util.JsonUtil;
import com.fasterxml.jackson.databind.ObjectMapper;
import net.sourceforge.plantuml.SourceStringReader;
import org.springframework.stereotype.Service;

import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Service
public class DocGeneratorService {

    private final S3UploadService s3UploadService;

    public DocGeneratorService(S3UploadService s3UploadService) {
        this.s3UploadService = s3UploadService;
    }

    public File generateDocsZip(ProjectMetadata pm) throws IOException {
        Path outDir = Files.createTempDirectory("autodoc_output_");

        // --- Generate README.md ---
        Path readme = outDir.resolve("README.md");
        String readmeText = buildReadme(pm);
        Files.writeString(readme, readmeText);

        // --- Generate UML ---
        Path puml = outDir.resolve("diagram.puml");
        String pumlText = buildPlantUml(pm);
        Files.writeString(puml, pumlText);

        Path umlPng = outDir.resolve("diagram.png");
        generateUmlPng(pumlText, umlPng);

        // --- Metadata JSON ---
        Path meta = outDir.resolve("metadata.json");
        Files.writeString(meta, JsonUtil.toJson(pm));

        Map<String, Object> qualityReport = new LinkedHashMap<>();
        Map<String, Object> analysis = DocQualityAnalyzer.analyzeDocText(readmeText);
        qualityReport.put("docAnalysis", analysis);
        qualityReport.put("similarMethods", DocQualityAnalyzer.detectSimilarMethods(pm.getClasses()));
        qualityReport.put("duplicateMethodBodies", DocQualityAnalyzer.detectDuplicateMethodBodies(pm.getClasses()));

        Path quality = outDir.resolve("quality_report.json");
        ObjectMapper mapper = new ObjectMapper();
        Files.writeString(quality, mapper.writerWithDefaultPrettyPrinter().writeValueAsString(qualityReport));

        Path swagger = outDir.resolve("openapi.json");
        Files.writeString(swagger, buildSwagger(pm));

        Path zip = outDir.resolveSibling(pm.getProjectName() + "_autodoc.zip");
        try (ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(zip))) {
            for (Path p : List.of(readme, puml, umlPng, meta, swagger, quality)) {
                zos.putNextEntry(new ZipEntry(p.getFileName().toString()));
                Files.copy(p, zos);
                zos.closeEntry();
            }
        }

        try {
            String key = "generated-docs/" + pm.getProjectName() + "_autodoc.zip";
            String s3Url = s3UploadService.uploadFile(zip.toFile(), key);
            System.out.println("Uploaded to S3: " + s3Url);
        } catch (Exception e) {
            System.err.println("Failed to upload to S3: " + e.getMessage());
        }

        return zip.toFile();
    }

    private String buildReadme(ProjectMetadata pm) {
        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(pm.getProjectName()).append("\n\n");
        sb.append("## Auto-generated Overview\n\n");
        sb.append("This documentation was automatically generated by AutoDoc.\n\n");

        for (ClassMetadata c : pm.getClasses()) {
            sb.append("### ").append(c.getClassName()).append(" (").append(c.getType()).append(")\n\n");
            sb.append(c.getAiDescription() != null ? c.getAiDescription() : c.getComment()).append("\n\n");
            if (c.getMethods() != null && !c.getMethods().isEmpty()) {
                sb.append("**Methods**:\n");
                for (MethodMeta m : c.getMethods()) {
                    sb.append("- `").append(m.getName()).append("(");
                    if (m.getParams() != null) sb.append(String.join(", ", m.getParams()));
                    sb.append(")` : ").append(m.getAiDescription() != null ? m.getAiDescription() : m.getComment());
                    sb.append("\n");
                }
                sb.append("\n");
            }
        }
        sb.append("## UML Diagram\n\n");
        sb.append("UML Diagram image is available as `diagram.png`.\n");
        return sb.toString();
    }

    private String buildPlantUml(ProjectMetadata pm) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        sb.append("skinparam classAttributeIconSize 0\n");

        for (ClassMetadata c : pm.getClasses()) {
            sb.append("class ").append(ensureId(c.getClassName())).append(" {\n");
            if (c.getFields() != null) {
                for (String f : c.getFields()) sb.append("  ").append(f.replaceAll("[\\[\\]]", "")).append("\n");
            }
            sb.append("}\n");
        }

        for (ClassMetadata c : pm.getClasses()) {
            if (c.getMethods() != null) {
                for (MethodMeta m : c.getMethods()) {
                    if (m.getRepositoryCalls() != null) {
                        for (String rc : m.getRepositoryCalls()) {
                            pm.getClasses().stream()
                                    .filter(x -> x.getClassName().toLowerCase().contains(rc.toLowerCase()) ||
                                            x.getClassName().toLowerCase().contains("repository"))
                                    .findFirst()
                                    .ifPresent(target ->
                                            sb.append(ensureId(c.getClassName())).append(" --> ")
                                                    .append(ensureId(target.getClassName())).append("\n"));
                        }
                    }
                }
            }
        }
        sb.append("@enduml\n");
        return sb.toString();
    }

    private void generateUmlPng(String pumlText, Path outputPng) throws IOException {
        try (FileOutputStream fos = new FileOutputStream(outputPng.toFile())) {
            SourceStringReader reader = new SourceStringReader(pumlText);
            reader.outputImage(fos);
        }
    }

    private String buildSwagger(ProjectMetadata pm) {
        StringBuilder sb = new StringBuilder();
        sb.append("{\n  \"openapi\": \"3.0.3\",\n  \"info\": {\n")
                .append("    \"title\": \"").append(pm.getProjectName()).append("\",\n")
                .append("    \"version\": \"1.0.0\",\n")
                .append("    \"description\": \"Auto-generated API documentation\"\n")
                .append("  },\n  \"components\": {\n")
                .append("    \"securitySchemes\": {\n")
                .append("      \"bearerAuth\": {\n")
                .append("        \"type\": \"http\",\n")
                .append("        \"scheme\": \"bearer\",\n")
                .append("        \"bearerFormat\": \"JWT\"\n")
                .append("      }\n    }\n  },\n")
                .append("  \"security\": [ { \"bearerAuth\": [] } ],\n")
                .append("  \"paths\": {\n");

        for (ClassMetadata c : pm.getClasses()) {
            if (!"Controller".equalsIgnoreCase(c.getType())) continue;
            if (c.getMethods() == null) continue;

            for (MethodMeta m : c.getMethods()) {
                String path = (m.getEndpoint() != null && !m.getEndpoint().isBlank())
                        ? m.getEndpoint() : ("/" + m.getName());
                String verb = (m.getHttpMethod() != null && !m.getHttpMethod().isBlank())
                        ? m.getHttpMethod().toLowerCase() : "get";

                sb.append("    \"").append(path).append("\": {\n")
                        .append("      \"").append(verb).append("\": {\n")
                        .append("        \"summary\": \"").append(escapeJson(m.getAiDescription() != null ? m.getAiDescription() : m.getComment())).append("\",\n")
                        .append("        \"requestBody\": {\n")
                        .append("          \"content\": {\n")
                        .append("            \"application/json\": {\n")
                        .append("              \"schema\": { \"type\": \"object\" },\n")
                        .append("              \"example\": { \"sampleField\": \"value\" }\n")
                        .append("            }\n          }\n        },\n")
                        .append("        \"responses\": {\n")
                        .append("          \"200\": {\n")
                        .append("            \"description\": \"Successful response\",\n")
                        .append("            \"content\": {\n")
                        .append("              \"application/json\": {\n")
                        .append("                \"example\": { \"status\": \"ok\" }\n")
                        .append("              }\n            }\n")
                        .append("          }\n        }\n")
                        .append("      }\n    },\n");
            }
        }

        if (sb.toString().endsWith(",\n")) {
            int last = sb.lastIndexOf(",\n");
            sb.delete(last, last + 2);
        }
        sb.append("  }\n}");
        return sb.toString();
    }

    private String escapeJson(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", " ");
    }

    private String ensureId(String s) {
        return s.replaceAll("[^A-Za-z0-9_]", "_");
    }
}